### ISSUE TITLE
GIT_COMMIT is ignored

### ISSUE THREAD

**Issue by quotschmacher** [tschuchortdev/cmake_git_clone#3]
if i use an example with git_commit, always the master branch is fetched. if i look at the cmake-code u used, the passed commit does not seem to be used, only the branch.

not working example:

>include(cmake/GitUtils.cmake)
>
>git_clone(
>	PROJECT_NAME	serial_lib
>	GIT_URL			https://github.com/itas109/CSerialPort
>	GIT_COMMIT		e6d0ae1
>)

**Comment by tschuchortdev** [comment]
That's right, seems I forgot to implement it. #4 should fix it.

**Comment by quotschmacher** [comment]
yes - for me #4 fixes it. shall i close this issue or wait till the pull request is accepted?

**Comment by tschuchortdev** [comment]
I will close it myself.
